# Generated by Django 5.0.7 on 2024-09-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(default='')),
                ('rating', models.PositiveIntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('genre', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=100)),
                ('image_url', models.URLField()),
                ('slug', models.SlugField(default='')),
                ('authors', models.ManyToManyField(to='books.author')),
            ],
        ),
    ]
