# Generated by Django 5.0.7 on 2024-09-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='author',
            name='year_of_birth',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
