# Generated by Django 5.0.7 on 2024-09-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_image_url_author_year_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(default='')),
                ('image_url', models.URLField(default='')),
                ('is_available', models.BooleanField(default=True)),
                ('type', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
